[package]
name = "rust-doc-ice-repro-2023-04-25"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"

[dependencies.clap]
version = "4.1.8"
features = [
  "derive",
]
